config/routes.rb
Rails.application.routes.draw do
  get 'about/index'
  get 'welcome/index'
  root 'welcome#index'
  get 'about/index'
  resources :articles do 
   resources :comments
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
	has_many :comments , dependent: :destroy
	mount_uploaders :image, ImageUploader
	serialize :image, JSON
	validates :title, presence: true,
                    length: { minimum: 5 }

end

app/models/articleshistory.rb
class Articleshistory < ApplicationRecord
	validates :title, presence: true,
                    length: { minimum: 5 }
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	 http_basic_authenticate_with name: "dhh", password: "secret", except: [:index, :show]

	def index
		@articles=Article.all
	end

	def show
		@article= Article.find(params[:id])
	end
	
	def new
		@article=Article.new
	end
	def edit
  		@article = Article.find(params[:id])
	end
 

	def create
		@article = Article.new(article_params)
		if @article.save
    		flash[:notice] = "Your Article was Created"
    		redirect_to @article
  		else
   		 render 'new'
  		end
	end
	def update
  		@article = Article.find(params[:id]) 
  		if @article.update(article_params)
     		flash[:notice] = "Your Article was Created"
     		redirect_to @article
  		else
    		render 'edit'
  		end
	end

	def destroy
  		@article = Article.find(params[:id])
  		@article.destroy 
  		redirect_to articles_path
	end
	private 
		def article_params
    		 params.require(:article).permit(:title, :body , {image:[]})
  		end
	
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	 
  http_basic_authenticate_with name: "dhh", password: "secret", only: :destroy
 
	def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    redirect_to article_path(@article)
  end
 def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to article_path(@article)
  end
 
  private
    def comment_params
      params.require(:comment).permit(:commenter, :body)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/about/index.html.erb
<h1>About#index</h1>
<p>Find me in app/views/about/index.html.erb</p>
<hi>About the Page</hi>
<h2 >Author Manifest </h2>
<p>The page created by Charalambos Pouroutides , the son and of Nicos Pouroutides as known as Pouroutos.
The Main purpose of this site is to present the memories of our comunity and transfer the message of "I never forget and keep fight" alive in the digital  era.</p>
<p> The structure of the page is :
	1) History Articles : Nicos Pouroutides writes about the stories of the community. Any story related with our community is welcome and should be emailed to Nicos Pouroutides (Pouroutos) for publishing . The site has not liability for any incosistency or any damages might occured caused by their pusblished articles.
	2) Announcements : In this section anouncement regarding events relevant to our community and Nicos Pouroutos should emailed about this.
	</p> 

app/views/articles/_form.html.erb
<%= form_with model: @article, local: true do |form| %>
 
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>
 
  <p>
    <%= form.label :body %><br>
    <%= form.trix_editor :body%>
  </p>
  
 <div class="form-group">
  <%= form.file_field :image,  multiple: true,class:'form-control-file'%>
</div>

  <p>
    <%= form.submit %>
  </p>
 
<% end %>

app/views/articles/edit.html.erb
<h1>Edit article</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<div class="container-fluid">
  <div class="raw">
    <div class="col-md-12"><h1>Listing articles</h1></div>
  </div>
</div>
 <%= link_to 'New article', new_article_path %>
  <% @articles.each do |article| %>
  <div class="container-fluid article-items">
 <div class="raw">
    <div class="col-md-3 "><img class=" article-index" src="<%= article.image[0] %>"></div>
    <div class="col-md-2"><%= article.title[0..50] %></div>
    <div class="col-md-3 article-text"><%=strip_tags(article.body[0..150]+" ...")%></div>
    <div class="col-md-1"><%= link_to 'Show', article_path(article) %></div>
    <div class="col-md-1"><%= link_to 'Edit', edit_article_path(article) %></div>
    <div class="col-md-2"><%= link_to 'Destroy', article_path(article),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></div>
 </div>
 </div>
 <% end %>

 

  

app/views/articles/new.html.erb
<h1>New article</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p class="comments">
  <strong><%= @article.title %></strong>
  
</p>
 <p class="article-body">
  <%=sanitize(@article.body, tags: %w(b strong em i a)).html_safe %>
</p>

<% if @article.image? %>
<div id="carouselwithIndicators" class="carousel slide w-50 article-pic" data-ride="carousel">
      
      <ol class="carousel-indicators">
           
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    
           <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
         
      <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
         
   </ol>
        
   <div class="carousel-inner">

       <div class="carousel-item active ">
  
        	<img class="d-block w-100" src=<%=@article.image[0]%> alt="First slide">

        </div>
         
     <%@article.image.each do |i| %>
    <div class="carousel-item ">
      <img class="d-block w-100 article-index" src= "<%=i%>" alt="First slide">
    </div>
     <% end %>
      
        
    <a class="carousel-control-prev" href="#carouselwithIndicators" role="button" data-slide="prev">
     
       <span class="carousel-control-prev-icon" aria-hidden="true"></span>
       
     <span class="sr-only">Previous</span>
            </a>
   
     <a class="carousel-control-next" href="#carouselwithIndicators" role="button" data-slide="next">
           
 	<span class="carousel-control-next-icon" aria-hidden="true"></span>
  
         <span class="sr-only">Next</span>

     </a>
  
	</div>
    
	  </div>
<% end %>


<div class="comments">
	<h2 >Comments</h2>
	<%= render @article.comments %>
	<h2>Add a comment:</h2>
	<%= render 'comments/form' %>
 </div>



<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>
<html lang="en">


      

  

app/views/comments/_comment.html.erb
<div class="comments">
<p>
  <strong>Commenter:</strong>
  <%= comment.commenter %>
</p>
 
<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>
<%= link_to 'Destroy Comment', [comment.article, comment],
               method: :delete,
               data: { confirm: 'Are you sure?' } %>
</div>

app/views/comments/_form.html.erb
<%= form_with(model: [ @article, @article.comments.build ], local: true) do |form| %>
  <p>
    <%= form.label :commenter %><br>
    <%= form.text_field :commenter %>
  </p>
  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Katokopia</title>

<!-- Meta tags -->
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
      <!-- Bootstrap CSS -->
      <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
       <%= csrf_meta_tags %>
    <!-- Latest compiled and minified CSS from Botttrap -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <!-- Optional theme Optional Bootstrap-->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
   <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <!-- Fonts library for images -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">
	  <!-- Latest compiled and minified JavaScript from Bootstrap -->
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
 <nav class="navbar fixed-top navbar-dark navbar-expand-sm navbar-template ">
  <%= link_to 'Katokopia', root_path , :class =>"navbar-brand"%>
    <div class="d-flex flex-row order-2 order-sm-3 ">
        <ul class="navbar-nav flex-row ">
            <li class="nav-item active"><a class="nav-link px-2" href="#"><i class="fab fa-facebook"></i></a></li>
            <li class="nav-item active"><a class="nav-link px-2" href="#"><i class="fab fa-twitter"></i></a></li>
            <li class="nav-item active"><a class="nav-link px-2" href="#"><i class="fab fa-youtube"></i></a></li>
            <li class="nav-item active"><a class="nav-link px-2" href="#"><i class="fab fa-github"></i></a></li>
        </ul>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown">
            <span class="navbar-toggler-icon "></span>
        </button>
    </div>
    <div class="collapse navbar-collapse order-3 order-sm-2  " id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
            <li class="nav-item active"><%= link_to 'History Articles', articles_path , :class =>"nav-link"%></li>
            <li class="nav-item active"><%= link_to 'About', about_index_path , :class =>"nav-link"%></li>
            <li class="nav-item active"><%= link_to 'Doxa Fc', articles_path , :class =>"nav-link"%></li>
            <li class="nav-item active"><%= link_to 'Anouncements', articles_path , :class =>"nav-link"%></li>
        </ul>
    </div>
  </nav>
  <div class="page-container">
    <%= yield %>
  </div>
  <div class="footer">
    <p>@copyrights: Katokopia.net</p>
</div>
      
  </body>
</html>

app/views/welcome/index.html.erb
<div class=" container  mainpic ">
	<div class="row">	
			<!-- remove height and width to show only  the image and fit in the main page without scroll-->
	<video height="5%" width="5%" autoplay loop muted class="img-circle col-md-12 "> 
  <source src="https://res.cloudinary.com/dwrltsmzw/video/upload/v1557389407/%CE%9A%CE%91%CE%A4%CE%A9%CE%9A%CE%9F%CE%A0%CE%99%CE%91_1969_-1974_03_24_-_03_27.5_rCdGiDTmnM0.mp4" type="video/mp4">
  
</video>

</div>
</div>

<div class=" container ">
	<div class="row">
		<div class="col-md-3  thumbnail ">
			<p>Accouncements</p>
			<img class="img-circle  img-circle" src="https://res.cloudinary.com/dwrltsmzw/image/upload/c_scale,w_10/v1549203518/samples/cloudinary-logo-vector.svg">
		</div>
		<div class="col-md-3 img-circle thumbnail">
			<p>DOXA FC</p>
			<img class="img-circle  img-circle " src="https://res.cloudinary.com/dwrltsmzw/image/upload/c_scale,w_10/v1549203518/samples/cloudinary-logo-vector.svg">
		</div>
		<div class="col-md-3 thumbnail">
			<p>PhotoRetro</p>
			<img class="img-circle  img-circle " src="https://res.cloudinary.com/dwrltsmzw/image/upload/c_scale,w_10/v1549203518/samples/cloudinary-logo-vector.svg">
		</div>
		<div class="col-md-3 thumbnail">
			<p>History Articles</p>
			<img class="img-circle  img-circle " src="" id="HistoryArticlesIndex">
			<%= link_to articles_path, id:"HistoryArticlesIndex" do %>
   			<%= image_tag "https://res.cloudinary.com/dwrltsmzw/image/upload/v1555706972/WEP-EKLHSIA-OLD.jpg" %>
			<% end %>
		</div>
	</div>
</div>